ALTER TABLE "BillingConfig" ADD COLUMN IF NOT EXISTS "billingTrialDays" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "BillingConfig" ADD COLUMN IF NOT EXISTS "billingGraceDaysAfterDue" INTEGER NOT NULL DEFAULT 0;
