import type { PlatformFeatureArea } from "./types";

export const rawPlatformFeatureAreasDa: PlatformFeatureArea[] = [
  {
    title: "Begivenheder og produktioner",
    summary: "Planlæg sæsonen og hold hver forestilling, prøve og note samlet i én levende post.",
    accent: "magenta",
    body:
      "Begivenheder er kernen i OrdoStage. Hver produktion får en varig post, som kunstneriske, produktions- og sceneteams åbner fra første samtale til load-out — med forestillinger, dokumenter, bemanding og spillestedskontekst samlet i stedet for spredte filer.",
    bullets: [
      "Opret og rediger begivenheder med titel, status, datoer, spillestedslinks og frie noter",
      "Administrer flere forestillinger pr. begivenhed — opførelser, prøver, get-ins og særlige calls",
      "Spor showtiming med start-, slut- og varighedsfelter, der forbliver konsistente på tværs af visninger",
      "Vedhæft produktionsdokumenter og downloads ved den begivenhed, de hører til",
      "Brug brugerdefinerede felter og kontakter på begivenhedsposten til partnere, agenter og co-producenter",
      "Knyt begivenheder til spillesteder, så program og drift er enige om, hvilket rum der er booket",
      "Åbn dedikerede faner for detaljer, forestillinger, spillestedsbooking, teams og personer på én side",
      "Se bemandingsoversigter pr. forestilling og pr. afdeling før call time",
      "Naviger fra begivenhedslisten eller dashboardet til det næste i din organisation",
      "Reducer dobbeltindtastning, når den samme produktion både er på turné og hjemme",
    ],
  },
  {
    title: "Planlægning og spillestedsbookinger",
    summary: "Uge- og månedskalendere, der samler kunstneriske holds, get-ins, turnéer og rumbookinger.",
    accent: "orange",
    body:
      "Planlægningen er, hvor konflikter kommer frem, før tech week. OrdoStage samler begivenhedsdatoer, interne spillestedsbookinger og turnéaktivitet i filtrerbare kalendervisninger, så produktionsledere og scenemanagement arbejder ud fra samme tidslinje.",
    bullets: [
      "Skift mellem uge- og månedvisninger på tværs af organisationens aktivitet",
      "Filtrer kalenderposter efter begivenhed, spillested, turné, prøve eller intern bookingtype",
      "Opret og rediger spillestedsbookinger med tidsgitre, der ligner velkendte kalenderværktøjer",
      "Se get-ins, forestillinger, holds og vedligehold samlet i ét billede",
      "Åbn poster på stedet for at justere tider uden at miste kontekst",
      "Opdag overlappende bookinger, før de bliver til showdagskriser",
      "Knyt planlægningsposter tilbage til den underliggende begivenhed eller spillestedspost",
      "Understøt interne bookinger adskilt fra offentligt program",
      "Brug konsistent håndtering af dato og tid for flerdagesproduktioner",
      "Giv scenemanagere en filtrerbar visning af det, der betyder noget på den dag, de fokuserer på",
    ],
  },
  {
    title: "Spillesteder og teknisk inventar",
    summary: "Hver scene, sal og studie med specifikationer, filer og egen bookingkalender.",
    accent: "violet",
    body:
      "Tekniske afdelinger vedligeholder spillestedsinventar, hvor bookinger lever. Rumspecifikationer, riggingnoter, plantegninger og fotos bliver på spillestedsposten, så gæstende produktioner og husets teams henter fra én autoritativ kilde.",
    bullets: [
      "Vedligehold et fuldt inventar af spillesteder og rum på tværs af én eller flere lokationer",
      "Gem adresse, kapacitet og teknisk metadata pr. spillested",
      "Vedhæft dokumenter, miniaturebilleder og filer til det rum, de beskriver",
      "Administrer scenemål og advarsler, når produktionsstørrelser overstiger rumgrænser",
      "Kør en dedikeret spillestedsbookingkalender pr. rum",
      "Rediger spillestedsdetaljer med strukturerede adresse- og kontaktfelter",
      "Understøt præsentationshuse, bygninger med flere rum og modtagende turnéspillesteder",
      "Reducer genafsendelse af den samme PDF, når en turné ankommer til en ny by",
      "Knyt spillestedsbookinger fra begivenheder, så kunst og drift ser det samme hold",
      "Giv head-of-stage og tekniske teams ét sted at opdatere specifikationer efter ombygninger",
    ],
  },
  {
    title: "Turnéer og tech riders",
    summary: "Ruteplanlægning, turnédage, delte planer og riderpakker genereret fra turnédata.",
    accent: "blue",
    body:
      "Turnéer tilføjer byer, lastbiler og lokale crews til hver beslutning. OrdoStage strukturerer turnéer med dage og forestillinger, producerer teknisk information til hvert stop og deler skrivebeskyttede planer, når partnere har brug for et link i stedet for fuld adgang.",
    bullets: [
      "Strukturer turnéer med dage, byer, spillesteder og tilknyttede forestillinger",
      "Se ruteplanlægning sammen med hjemmeprogram, når en forestilling både turnerer og har base",
      "Generer og del tech riders fra turnédata til lokale produktionsteams",
      "Publicer offentlige turnéplanlinks til artister, agenter og partnere",
      "Tilbyd personlige turnévisninger, når nogen kun har brug for deres del af vejen",
      "Hold turnédetaljer tilgængelige for produktion uden genindtastning i regneark",
      "Koordiner turnédatoer med spillestedsbookinger og produktionsdeadlines",
      "Opdater én gang i OrdoStage — alle med linket ser aktuelle datoer",
      "Reducer “hvilken riderversion er det?”-øjeblikke, når lastbilen ruller ind",
      "Afstem gæstende produktionskrav med hvert spillesteds faktiske inventar",
    ],
  },
  {
    title: "Bemanding og showjobs",
    summary: "Behov, tildelinger og afdelingsvisninger bygget til, hvordan forestillinger faktisk bemandes.",
    accent: "magenta",
    body:
      "Bemanding forbinder personlisten til hver forestilling. Sæt jobs op efter afdeling, spor hvem der er bekræftet, og se med et blik, hvor I mangler folk — med de samme data, som HR vedligeholder, og scenemanagement stoler på showdagen.",
    bullets: [
      "Definer showjobs med roller, afdelinger og planlagte timer pr. forestilling",
      "Tildel personer fra organisationens liste til hvert job på en forestilling",
      "Se bemanding-OK-indikatorer og huller pr. afdeling før premiere",
      "Gennemgå teamnoter og overleveringsinformation knyttet til begivenheder",
      "Brug bemandingvisninger designet til performanceorganisationer, ikke generiske HR-værktøjer",
      "Knyt tildelinger til den begivenhed og forestilling, de understøtter",
      "Reducer sidste-øjebliks-opkald, fordi nogen arbejdede ud fra en forældet liste",
      "Understøt flere teams og noter pr. begivenhed til komplekse produktioner",
      "Afstem crewkrav med produktionsplanlægger og planlægningsdata",
      "Giv scenemanagere det samme tildelingsbillede, som kontoret bruger",
    ],
  },
  {
    title: "Personer, teams og tilladelser",
    summary: "Én liste, strukturerede teams, invitationer og tilladelsesgrupper til hver afdeling.",
    accent: "violet",
    body:
      "Personposter driver alt andet. HR og drift onboarder medlemmer én gang, organiserer dem i teams og tilladelsesgrupper og styrer, hvem der kan se eller redigere begivenheder, spillesteder, tid og fakturering — uden parallelle regneark.",
    bullets: [
      "Vedligehold profiler med navne, fotos, kontaktoplysninger og ansættelseskontekst",
      "Organiser personer i teams og afdelinger, der afspejler jeres hus eller turné",
      "Inviter nye medlemmer via e-mail og tildel dem til den rigtige organisation",
      "Genbrug den samme person på tværs af begivenheder, bemanding, tidsregistrering og dokumenter",
      "Konfigurer tilladelsesgrupper med granulær læse- og skriveadgang pr. område",
      "Understøt frivillige, freelancere og ansatte med passende tillidsgrænser",
      "Administrer organisationsmedlemskab og multi-org-adgang til turnévirksomheder",
      "Hold teammedlemskab opdateret, når personer skifter rolle midt i sæsonen",
      "Styr, hvem der ser fakturering, produktion, spillesteder og tidsmoduler",
      "Reducer dobbeltposter, når nogen arbejder på flere produktioner",
    ],
  },
  {
    title: "Tidsregistrering og rapporter",
    summary: "Crew og personale registrerer timer på rigtigt arbejde; økonomi eksporterer strukturerede data.",
    accent: "yellow",
    body:
      "Tidsregistreringer knyttes til begivenheder, forestillinger, roller og kategorier — ikke en separat timeseddelapp. Ledere gennemgår aktivitet i kontekst; økonomi kører rapporter og eksporter, når løn eller omkostninger skal have tal knyttet til faktiske produktioner.",
    bullets: [
      "Registrer timer mod begivenheder, produktioner og bemandingstildelinger",
      "Kategoriser tid til løn, omkostninger og interne rapporteringsregler",
      "Gennemgå registreringer i tidsvisninger filtreret efter person, begivenhed eller periode",
      "Kør tidsrapporter til lønforberedelse og retrospektiv produktionsomkostning",
      "Eksporter data, når økonomi skal afstemme i eksterne systemer",
      "Knyt rapporterede timer til personposten, som HR allerede vedligeholder",
      "Understøt turnécrews, der registrerer mod turnédage og bystop",
      "Giv produktionsledere indsigt i arbejdskraft mod planen",
      "Reducer hukommelsesbaserede timesedler efter lange tech weeks eller turnéetaper",
      "Hold ledere og økonomi aligned på de samme underliggende tal",
    ],
  },
  {
    title: "Produktionsplanlægger",
    summary: "Faser, opgaver, omkostninger, crewlinjer og PDF-planer på en produktionstidslinje.",
    accent: "orange",
    body:
      "Produktionsplanlæggeren er til build- og tech-milepæle, der ligger ved siden af det kunstneriske kalender. Planlæg faser på en Gantt-lignende tidslinje, vedhæft omkostninger og crew, åbn opgavedetaljer og eksporter en PDF, når partnere har brug for en udskrivbar plan.",
    bullets: [
      "Opret produktioner og tilføj planlinjer for faser, opgaver og omkostningsposter",
      "Se en interaktiv Gantt-tidslinje med zoom og datointervalkontroller",
      "Spor opgavekategorier, kritisk sti og milepæle på tværs af produktionen",
      "Åbn opgavesider for fasekontekst, redigeringer og sletning, når planer ændres",
      "Administrer budget- og crewpaneler knyttet til den valgte produktion",
      "Registrer planlagte og faktiske omkostninger ved den tidslinje, de understøtter",
      "Download produktionsplan-PDF'er til møder og eksterne partnere",
      "Afstem planlægningsdatoer med begivenheds- og schedule-data, organisationen allerede bruger",
      "Understøt langvarige builds, hvor tech week kun er ét kapitel",
      "Giv produktionsledere én tidslinje i stedet for en mappe med versioner",
    ],
  },
  {
    title: "Delte kalendere og organisationskonto",
    summary: "Publicer skrivebeskyttede visninger, administrer fakturering og hold virksomhedsoplysninger samlet.",
    accent: "blue",
    body:
      "Ikke alle har brug for login. Delte kalendere og offentlige turnélinks lader partnere se aktuelle datoer sikkert. Organisationsejere administrerer planer, pladser og virksomhedsfaktureringsoplysninger i kontoområdet — sammen med det arbejde, hele virksomheden kører i OrdoStage.",
    bullets: [
      "Publicer delte kalendere, når eksterne partnere har brug for en skrivebeskyttet visning",
      "Eksporter eller koordiner udadtil, mens OrdoStage forbliver kilden til sandhed",
      "Del offentlige turnéplaner uden at give adgang til hele organisationen",
      "Gem virksomheds-, faktura- og faktureringskontaktoplysninger i organisationskontoen",
      "Vælg Flex- eller Yearly-fakturering med pladsniveauer, der passer til teamstørrelsen",
      "Administrer organisationsindstillinger, medlemmer og ejere i ét kontoområde",
      "Send e-mailinvitationer og onboard nye medlemmer i den rigtige organisation",
      "Brug dashboardet til at se kommende begivenheder og aktivitet med et blik",
      "Skift mellem organisationer, når virksomheden driver flere enheder",
      "Styr, hvem der kan administrere fakturering og medlemskab som organisationsejere",
    ],
  },
];
