import type { PlatformFeatureArea } from "./types";

export const rawPlatformFeatureAreasDe: PlatformFeatureArea[] = [
  {
    title: "Events und Produktionen",
    summary: "Planen Sie die Saison und halten Sie jede Vorstellung, Probe und Notiz in einem lebendigen Datensatz zusammen.",
    accent: "magenta",
    body:
      "Events sind das Zentrum von OrdoStage. Jede Produktion erhält einen dauerhaften Datensatz, den künstlerische, Produktions- und Bühnenteams von der ersten Besprechung bis zum Load-out nutzen — mit Vorstellungen, Dokumenten, Besetzung und Spielstättenkontext an einem Ort statt verstreuter Dateien.",
    bullets: [
      "Events mit Titel, Status, Terminen, Spielstättenlinks und freien Notizen anlegen und bearbeiten",
      "Mehrere Vorstellungen pro Event verwalten — Aufführungen, Proben, Get-ins und Sondercalls",
      "Show-Timing mit Start-, End- und Dauerfeldern verfolgen, die in allen Ansichten konsistent bleiben",
      "Produktionsdokumente und Downloads direkt beim zugehörigen Event anhängen",
      "Benutzerdefinierte Felder und Kontakte im Event-Datensatz für Partner, Agenten und Co-Produzenten nutzen",
      "Events mit Spielstätten verknüpfen, damit Programm und Betrieb dieselbe Raumbuchung sehen",
      "Dedizierte Tabs für Details, Vorstellungen, Spielstättenbuchung, Teams und Personen auf einer Seite öffnen",
      "Besetzungsübersichten pro Vorstellung und Abteilung vor Call Time einsehen",
      "Von der Event-Liste oder dem Dashboard zu den nächsten Terminen Ihrer Organisation navigieren",
      "Doppeleingaben reduzieren, wenn dieselbe Produktion auf Tour und zu Hause läuft",
    ],
  },
  {
    title: "Terminplan und Spielstättenbuchungen",
    summary: "Wochen- und Monatskalender, die künstlerische Holds, Get-ins, Touren und Raumbuchungen vereinen.",
    accent: "orange",
    body:
      "Im Terminplan werden Konflikte sichtbar, bevor die Tech Week beginnt. OrdoStage führt Event-Termine, interne Spielstättenbuchungen und Tour-Aktivitäten in filterbaren Kalenderansichten zusammen, damit Produktionsleitung und Stage Management auf derselben Timeline arbeiten.",
    bullets: [
      "Zwischen Wochen- und Monatsansichten der gesamten Organisationsaktivität wechseln",
      "Kalendereinträge nach Event, Spielstätte, Tour, Probe oder internem Buchungstyp filtern",
      "Spielstättenbuchungen mit Zeitgittern erstellen und bearbeiten, wie aus vertrauten Kalender-Tools",
      "Get-ins, Vorstellungen, Holds und Wartung in einem Gesamtbild sehen",
      "Einträge direkt öffnen und Zeiten anpassen, ohne den Kontext zu verlieren",
      "Überlappende Buchungen erkennen, bevor sie zu Showtag-Krisen werden",
      "Terminplaneinträge mit dem zugrunde liegenden Event oder Spielstätten-Datensatz verbinden",
      "Interne Buchungen getrennt vom öffentlichen Event-Programm unterstützen",
      "Konsistente Datums- und Zeitbehandlung für mehrtägige Produktionen nutzen",
      "Stage Managern eine filterbare Ansicht dessen geben, was am relevanten Tag zählt",
    ],
  },
  {
    title: "Spielstätten und technisches Inventar",
    summary: "Jede Bühne, jeder Saal und jedes Studio mit Spezifikationen, Dateien und eigenem Buchungskalender.",
    accent: "violet",
    body:
      "Technische Abteilungen pflegen das Spielstätten-Inventar, in dem Buchungen leben. Raumspezifikationen, Rigging-Notizen, Grundrisse und Fotos bleiben am Spielstätten-Datensatz, damit Gastproduktionen und Hausteams aus einer autoritativen Quelle schöpfen.",
    bullets: [
      "Vollständiges Inventar von Spielstätten und Räumen über einen oder mehrere Standorte pflegen",
      "Adresse, Kapazität und technische Metadaten pro Spielstätte speichern",
      "Dokumente, Vorschaubilder und Dateien dem beschriebenen Raum zuordnen",
      "Bühnenmaße und Warnungen verwalten, wenn Produktionsgrößen Raumgrenzen überschreiten",
      "Einen dedizierten Spielstätten-Buchungskalender pro Raum führen",
      "Spielstättendetails mit strukturierten Adress- und Kontaktfeldern bearbeiten",
      "Präsentationshäuser, Mehr-Raum-Gebäude und empfangende Tour-Spielstätten unterstützen",
      "Wiederholtes Versenden derselben PDF reduzieren, wenn eine Tour in einer neuen Stadt ankommt",
      "Spielstättenbuchungen von Events verknüpfen, damit Kunst und Betrieb denselben Hold sehen",
      "Head of Stage und Technik-Teams einen Ort geben, Spezifikationen nach Umbauten zu aktualisieren",
    ],
  },
  {
    title: "Touren und Tech Riders",
    summary: "Routing, Tourtage, geteilte Pläne und Rider-Pakete, die aus Tourdaten generiert werden.",
    accent: "blue",
    body:
      "Tournees fügen jeder Entscheidung Städte, Lkw und lokale Crews hinzu. OrdoStage strukturiert Touren mit Tagen und Vorstellungen, erstellt Tech-Informationen für jeden Stopp und teilt schreibgeschützte Pläne, wenn Partner einen Link statt vollem Zugang brauchen.",
    bullets: [
      "Touren mit Tagen, Städten, Spielstätten und verknüpften Vorstellungen strukturieren",
      "Routing neben dem Heimprogramm sehen, wenn eine Show sowohl tourt als auch residiert",
      "Tech Riders aus Tourdaten generieren und mit lokalen Produktionsteams teilen",
      "Öffentliche Tour-Plan-Links für Künstler, Agenten und Partner veröffentlichen",
      "Persönliche Tour-Ansichten anbieten, wenn jemand nur seinen Teil der Reise braucht",
      "Tour-Details für die Produktion zugänglich halten, ohne Tabellen neu einzutippen",
      "Tour-Termine mit Spielstättenbuchungen und Produktionsfristen koordinieren",
      "Einmal in OrdoStage aktualisieren — alle mit dem Link sehen aktuelle Termine",
      "„Welche Rider-Version ist das?“-Momente reduzieren, wenn der Lkw eintrifft",
      "Anforderungen der Gastproduktion mit dem tatsächlichen Inventar jeder Spielstätte abstimmen",
    ],
  },
  {
    title: "Besetzung und Show-Jobs",
    summary: "Anforderungen, Zuweisungen und Abteilungsansichten, gebaut für die tatsächliche Crew-Planung.",
    accent: "magenta",
    body:
      "Besetzung verbindet den Personenstamm mit jeder Vorstellung. Jobs nach Abteilung aufbauen, bestätigte Personen verfolgen und auf einen Blick sehen, wo Lücken sind — mit denselben Daten, die HR pflegt und Stage Management am Showtag vertraut.",
    bullets: [
      "Show-Jobs mit Rollen, Abteilungen und geplanten Stunden pro Vorstellung definieren",
      "Personen aus dem Organisationsstamm jedem Job einer Vorstellung zuweisen",
      "Besetzungs-OK-Indikatoren und Lücken nach Abteilung vor der Premiere sehen",
      "Team-Notizen und Übergabeinformationen an Events einsehen",
      "Besetzungsansichten nutzen, die für Performance-Organisationen entwickelt wurden, nicht generische HR-Tools",
      "Zuweisungen mit dem Event und der Vorstellung verbinden, die sie unterstützen",
      "Last-Minute-Anrufe reduzieren, weil jemand mit einer veralteten Liste arbeitete",
      "Mehrere Teams und Notizen pro Event für komplexe Produktionen unterstützen",
      "Crew-Anforderungen mit Produktionsplaner- und Terminplandaten abstimmen",
      "Stage Managern dasselbe Zuweisungsbild geben, das das Büro nutzt",
    ],
  },
  {
    title: "Personen, Teams und Berechtigungen",
    summary: "Ein Stamm, strukturierte Teams, Einladungen und Berechtigungsgruppen für jede Abteilung.",
    accent: "violet",
    body:
      "Personendatensätze speisen alles andere. HR und Betrieb nehmen Mitglieder einmal auf, organisieren sie in Teams und Berechtigungsgruppen und steuern, wer Events, Spielstätten, Zeit und Abrechnung sehen oder bearbeiten darf — ohne parallele Tabellen.",
    bullets: [
      "Profile mit Namen, Fotos, Kontaktdaten und Beschäftigungskontext pflegen",
      "Personen in Teams und Abteilungen organisieren, die Ihr Haus oder Ihre Tour widerspiegeln",
      "Neue Mitglieder per E-Mail einladen und der richtigen Organisation zuweisen",
      "Dieselbe Person über Events, Besetzung, Zeiterfassung und Dokumente wiederverwenden",
      "Berechtigungsgruppen mit granularer Lese- und Schreibberechtigung pro Bereich konfigurieren",
      "Freiwillige, Freelancer und Festangestellte mit passenden Vertrauensgrenzen unterstützen",
      "Organisationsmitgliedschaft und Multi-Org-Zugang für Tour-Unternehmen verwalten",
      "Team-Mitgliedschaft aktuell halten, wenn Personen mitten in der Saison die Rolle wechseln",
      "Steuern, wer Abrechnung, Produktion, Spielstätten und Zeit-Module sieht",
      "Doppeleinträge reduzieren, wenn jemand an mehreren Produktionen arbeitet",
    ],
  },
  {
    title: "Zeiterfassung und Berichte",
    summary: "Crew und Personal erfassen Stunden für echte Arbeit; Finanzen exportieren strukturierte Daten.",
    accent: "yellow",
    body:
      "Zeiteinträge verknüpfen sich mit Events, Vorstellungen, Rollen und Kategorien — nicht mit einer separaten Stundenzettel-App. Manager prüfen Aktivität im Kontext; Finanzen erstellen Berichte und Exporte, wenn Lohn oder Kalkulation Zahlen brauchen, die an echte Produktionen gebunden sind.",
    bullets: [
      "Stunden gegen Events, Produktionen und Besetzungszuweisungen erfassen",
      "Zeit für Lohn, Kalkulation und interne Berichtsregeln kategorisieren",
      "Einträge in Zeiterfassungsansichten nach Person, Event oder Zeitraum prüfen",
      "Zeitberichte für Lohnvorbereitung und retrospektive Produktionskalkulation erstellen",
      "Daten exportieren, wenn Finanzen in externen Systemen abstimmen müssen",
      "Gemeldete Stunden mit dem Personendatensatz verbinden, den HR bereits pflegt",
      "Tour-Crews unterstützen, die gegen Tourtage und Städtestopps erfassen",
      "Produktionsleitern Einblick in Arbeitszeit gegen den Plan geben",
      "Gedächtnisbasierte Stundenzettel nach langen Tech Weeks oder Tour-Etappen reduzieren",
      "Manager und Finanzen auf dieselben zugrunde liegenden Zahlen ausrichten",
    ],
  },
  {
    title: "Produktionsplaner",
    summary: "Phasen, Aufgaben, Kosten, Crew-Zeilen und PDF-Pläne auf einer Produktions-Timeline.",
    accent: "orange",
    body:
      "Der Produktionsplaner ist für Build- und Tech-Meilensteine neben dem künstlerischen Kalender. Phasen auf einer Gantt-ähnlichen Timeline planen, Kosten und Crew anhängen, Aufgabendetails öffnen und ein PDF exportieren, wenn Partner einen druckbaren Plan brauchen.",
    bullets: [
      "Produktionen anlegen und Planzeilen für Phasen, Aufgaben und Kostenpositionen hinzufügen",
      "Eine interaktive Gantt-Timeline mit Zoom und Datumsbereichssteuerung ansehen",
      "Aufgabenkategorien, kritischen Pfad und Meilensteine über die Produktion verfolgen",
      "Aufgabenseiten für Phasenkontext, Bearbeitungen und Löschungen bei Planänderungen öffnen",
      "Budget- und Crew-Panels zur ausgewählten Produktion verwalten",
      "Geplante und tatsächliche Kosten neben der Timeline erfassen, die sie unterstützen",
      "Produktionsplan-PDFs für Meetings und externe Partner herunterladen",
      "Planer-Termine mit Event- und Terminplandaten abstimmen, die die Organisation bereits nutzt",
      "Langfristige Builds unterstützen, bei denen die Tech Week nur ein Kapitel ist",
      "Produktionsleitern eine Timeline statt eines Ordners mit Versionen geben",
    ],
  },
  {
    title: "Geteilte Kalender und Organisationskonto",
    summary: "Schreibgeschützte Ansichten veröffentlichen, Abrechnung verwalten und Firmendaten zentral halten.",
    accent: "blue",
    body:
      "Nicht jeder braucht ein Login. Geteilte Kalender und öffentliche Tour-Links lassen Partner aktuelle Termine sicher einsehen. Organisationsinhaber verwalten Pläne, Plätze und Firmen-Abrechnungsdaten im Konto-Bereich — neben der Arbeit, die das gesamte Unternehmen in OrdoStage betreibt.",
    bullets: [
      "Geteilte Kalender veröffentlichen, wenn externe Partner eine schreibgeschützte Ansicht brauchen",
      "Nach außen exportieren oder koordinieren, während OrdoStage die Quelle der Wahrheit bleibt",
      "Öffentliche Tour-Pläne teilen, ohne Zugang zur gesamten Organisation zu gewähren",
      "Firmen-, Rechnungs- und Abrechnungskontaktdaten im Organisationskonto speichern",
      "Flex- oder Yearly-Abrechnung mit Sitzplatz-Stufen passend zur Teamgröße wählen",
      "Organisationseinstellungen, Mitglieder und Inhaber in einem Konto-Bereich verwalten",
      "E-Mail-Einladungen senden und neue Mitglieder in der richtigen Organisation onboarden",
      "Das Dashboard nutzen, um kommende Events und Aktivität auf einen Blick zu sehen",
      "Zwischen Organisationen wechseln, wenn Ihr Unternehmen mehrere Einheiten betreibt",
      "Steuern, wer als Organisationsinhaber Abrechnung und Mitgliedschaft verwalten darf",
    ],
  },
];
