-- AlterTable
ALTER TABLE "Person" ADD COLUMN IF NOT EXISTS "workName" TEXT;
ALTER TABLE "Person" ADD COLUMN IF NOT EXISTS "workEmail" TEXT;
ALTER TABLE "Person" ADD COLUMN IF NOT EXISTS "workPhone" TEXT;
