// Re-export all shared types from the backend
export type {
  Venue,
  VenueDocument,
  CreateVenue,
  Person,
  CreatePerson,
  Department,
  Event,
  EventShow,
  EventShowJob,
  CreateEvent,
  EventDetail,
  EventTeam,
  EventTeamNote,
  EventPerson,
  Document,
  Calendar,
  ProductionCostCategory,
  ProductionCostLine,
  CreateProductionCostLine,
  UpdateProductionCostLine,
  ProductionPlannerTask,
  ProductionPlannerGanttLine,
  ProductionPlannerRow,
  ProductionPlannerResponse,
  ProductionPhaseKind,
  Production,
  ProductionPerson,
  ProductionTeam,
  ProductionPhase,
  ProductionPhaseDocument,
  ProductionPhaseCategory,
  CreateProduction,
  CreateProductionPhase,
  UpdateProductionPhase,
} from "../../../backend/src/types";
