// Re-export all shared types from the backend
export type {
  Venue,
  VenueDocument,
  CreateVenue,
  Person,
  CreatePerson,
  Event,
  EventShow,
  EventShowJob,
  CreateEvent,
  EventDetail,
  EventTeam,
  EventTeamNote,
  EventPerson,
  Document,
  Calendar,
  ProductionCostCategory,
  ProductionCostLine,
  CreateProductionCostLine,
  UpdateProductionCostLine,
  ProductionPlannerTask,
  ProductionPlannerRow,
  ProductionPlannerResponse,
} from "../../../backend/src/types";
